// Tour catalog data for bacalarallinone.tours
// Schema notes:
//   pickupPoints[] — origin options with flat USD surcharge over priceAdult/priceKid.
//   First entry is the default (surcharge 0) and matches `location`.
//   Rendered on detail page as a pickup selector.
window.TOURS = [
  {
    id: "sailboat-bacalar",
    slug: "bacalar-sailboat-sunset",
    title: { en: "Seven-Color Sailboat Tour", es: "Velero Siete Colores" },
    tagline: { en: "3hrs gliding across the lagoon of seven colors · stromatolites + pirate channel", es: "3 hrs navegando la laguna de los siete colores · estromatolitos + canal de los piratas" },
    category: "lagoon",
    audience: ["regular"],
    location: "Bacalar Lagoon",
    duration: 3,
    priceAdult: 65,
    priceKid: 35,
    rating: 4.9,
    reviews: 412,
    tags: ["lagoon", "sailing", "sunset", "stromatolites"],
    includes: ["Captain & crew", "Fresh fruit & drinks", "Snorkel at stromatolites", "Swim at pirate channel"],
    meet: { en: "Bacalar public dock, 15 min before departure", es: "Muelle público de Bacalar, 15 min antes" },
    times: ["09:00", "13:00", "16:30"],
    color: "lagoon",
    phLabel: "SAILBOAT · LAGOON",
    pickupPoints: [
      { label: { en: "Bacalar · public dock", es: "Bacalar · muelle público" }, surcharge: 0,  etaMin: 0  },
      { label: { en: "Bacalar · hotel zone",  es: "Bacalar · zona hotelera"  }, surcharge: 5,  etaMin: 10 }
    ]
  },
  {
    id: "pontoon-rapids",
    slug: "pontoon-piratas-rapidos-cocalitos",
    title: { en: "Private Pontoon · Piratas, Rápidos & Cocalitos", es: "Pontón Privado · Piratas, Rápidos y Cocalitos" },
    tagline: { en: "Private pontoon, floating ceviche, stromatolites + pirate channel + cenote Cocalitos", es: "Pontón privado, ceviche flotante, estromatolitos + canal piratas + cenote Cocalitos" },
    category: "lagoon",
    audience: ["regular"],
    location: "Bacalar Lagoon",
    duration: 4,
    priceAdult: 95,
    priceKid: 55,
    rating: 4.8,
    reviews: 287,
    tags: ["private", "lagoon", "lunch", "stromatolites"],
    includes: ["Private pontoon (up to 10)", "Ceviche & cold drinks", "Stromatolites stop", "Cenote Cocalitos entry", "Pirate channel swim"],
    times: ["09:30", "14:00"],
    color: "deep",
    phLabel: "PONTOON · PIRATAS",
    pickupPoints: [
      { label: { en: "Bacalar · public dock", es: "Bacalar · muelle público" }, surcharge: 0,  etaMin: 0  },
      { label: { en: "Bacalar · hotel zone",  es: "Bacalar · zona hotelera"  }, surcharge: 5,  etaMin: 10 }
    ]
  },
  {
    id: "kayak-sunrise",
    slug: "kayak-sunrise-bacalar",
    title: { en: "Sunrise Kayak & Paddleboard", es: "Kayak y Paddle al Amanecer" },
    tagline: { en: "Glassy water, pelicans, zero crowds", es: "Agua de cristal, pelícanos, cero multitud" },
    category: "lagoon",
    audience: ["regular"],
    location: "Bacalar Lagoon",
    duration: 2,
    priceAdult: 35,
    priceKid: 20,
    rating: 4.9,
    reviews: 523,
    tags: ["lagoon", "sunrise", "active"],
    includes: ["Kayak or SUP", "Guide", "Coffee & pastries", "Waterproof bag"],
    times: ["06:00", "07:00"],
    color: "lagoon",
    phLabel: "KAYAK · SUP",
    pickupPoints: [
      { label: { en: "Bacalar · public dock", es: "Bacalar · muelle público" }, surcharge: 0, etaMin: 0 }
    ]
  },
  {
    id: "cenotes-tour",
    slug: "cenotes-azul-negro-cocalitos",
    title: { en: "Cenotes · Azul, Negro & Cocalitos", es: "Cenotes · Azul, Negro y Cocalitos" },
    tagline: { en: "Three Bacalar cenotes, jungle trails, zipline finish", es: "Tres cenotes de Bacalar, selva, tirolesa al final" },
    category: "adventure",
    audience: ["regular"],
    location: "Near Bacalar",
    duration: 6,
    priceAdult: 110,
    priceKid: 65,
    rating: 4.7,
    reviews: 198,
    tags: ["cenote", "adventure", "swimming"],
    includes: ["Van transfer", "Entries: Azul + Negro + Cocalitos", "Lunch", "Zipline"],
    times: ["08:00"],
    color: "jungle",
    phLabel: "CENOTES · JUNGLE",
    pickupPoints: [
      { label: { en: "Bacalar · hotel zone",  es: "Bacalar · zona hotelera"  }, surcharge: 0,  etaMin: 0  },
      { label: { en: "Mahahual pier",          es: "Muelle Mahahual"          }, surcharge: 40, etaMin: 75 }
    ]
  },
  {
    id: "chacchoben-port",
    slug: "chacchoben-ruins-mahahual",
    title: { en: "Chacchoben Ruins · Port Express", es: "Ruinas Chacchoben · Exprés Puerto" },
    tagline: { en: "3hrs at Mayan ruins, back to ship by 2pm — guaranteed", es: "3 hrs en ruinas mayas, de vuelta al barco a las 2pm" },
    category: "ruins",
    audience: ["port", "regular"],
    location: "45 min from Mahahual",
    duration: 4,
    priceAdult: 75,
    priceKid: 40,
    rating: 4.8,
    reviews: 1240,
    tags: ["port-friendly", "ruins", "mayan"],
    includes: ["AC van pickup at pier", "Certified guide", "Entry fees", "Water"],
    meet: { en: "Mahahual cruise pier — meeting agent with sign", es: "Muelle de cruceros Mahahual — agente con letrero" },
    times: ["08:30", "10:30"],
    portReturn: "14:00",
    color: "clay",
    phLabel: "CHACCHOBEN · RUINS",
    pickupPoints: [
      { label: { en: "Mahahual cruise pier",   es: "Muelle cruceros Mahahual" }, surcharge: 0,  etaMin: 10 },
      { label: { en: "Costa Maya resorts",     es: "Resorts Costa Maya"       }, surcharge: 10, etaMin: 20 },
      { label: { en: "Bacalar · hotel zone",   es: "Bacalar · zona hotelera"  }, surcharge: 15, etaMin: 45 }
    ]
  },
  {
    id: "kohunlich",
    slug: "kohunlich-masks-temple",
    title: { en: "Kohunlich · Temple of Masks", es: "Kohunlich · Templo de los Mascarones" },
    tagline: { en: "Giant stucco masks in deep jungle · small group + archaeologist", es: "Mascarones de estuco en selva profunda · grupo pequeño + arqueólogo" },
    category: "ruins",
    audience: ["regular", "port"],
    location: "2hrs from Bacalar",
    duration: 7,
    priceAdult: 110,
    priceKid: 60,
    rating: 4.9,
    reviews: 167,
    tags: ["ruins", "mayan", "jungle", "archaeologist"],
    includes: ["Van & driver", "Bilingual archaeologist", "Entry", "Regional lunch"],
    times: ["08:00"],
    color: "jungle",
    phLabel: "KOHUNLICH · MAYA",
    pickupPoints: [
      { label: { en: "Bacalar · hotel zone",  es: "Bacalar · zona hotelera"  }, surcharge: 0,  etaMin: 0  },
      { label: { en: "Mahahual cruise pier",  es: "Muelle cruceros Mahahual" }, surcharge: 15, etaMin: 30 },
      { label: { en: "Chetumal",              es: "Chetumal"                 }, surcharge: 0,  etaMin: 45 }
    ]
  },
  {
    id: "tulum-day",
    slug: "tulum-ruins-from-bacalar",
    title: { en: "Tulum Ruins · from Bacalar", es: "Ruinas de Tulum · desde Bacalar" },
    tagline: { en: "Cliff-top ruins + cenote + beach · long day-trip from Bacalar", es: "Ruinas sobre acantilado + cenote + playa · día largo desde Bacalar" },
    category: "ruins",
    audience: ["regular"],
    location: "From Bacalar (~4h each way)",
    duration: 10,
    priceAdult: 180,
    priceKid: 95,
    rating: 4.7,
    reviews: 892,
    tags: ["ruins", "beach", "cenote", "from-bacalar"],
    includes: ["Transfer", "Guide", "All entries incl. Jaguar Park bracelet", "Lunch"],
    times: ["06:30"],
    color: "lagoon",
    phLabel: "TULUM · FROM BACALAR",
    pickupPoints: [
      { label: { en: "Bacalar · hotel zone", es: "Bacalar · zona hotelera"  }, surcharge: 0,  etaMin: 0  },
      { label: { en: "Mahahual pier",        es: "Muelle Mahahual"          }, surcharge: 40, etaMin: 75 }
    ]
  },
  {
    id: "tulum-local",
    slug: "tulum-ruins-local",
    title: { en: "Tulum Ruins · Local", es: "Ruinas de Tulum · Local" },
    tagline: { en: "Cliff-top ruins with a local guide — short 2hr visit", es: "Ruinas de acantilado con guía local — visita de 2 hrs" },
    category: "ruins",
    audience: ["regular"],
    location: "From Tulum town",
    duration: 3,
    priceAdult: 45,
    priceKid: 25,
    rating: 4.7,
    reviews: 320,
    tags: ["ruins", "local", "tulum"],
    includes: ["Bilingual local guide", "Jaguar Park entry + bracelet", "Water"],
    times: ["07:00", "09:00", "11:00", "15:00"],
    color: "lagoon",
    phLabel: "TULUM · LOCAL",
    pickupPoints: [
      { label: { en: "Tulum town · centre",   es: "Tulum · centro"           }, surcharge: 0,  etaMin: 0  },
      { label: { en: "Tulum hotel zone",      es: "Tulum · zona hotelera"    }, surcharge: 10, etaMin: 15 }
    ]
  },
  {
    id: "chichen-itza",
    slug: "chichen-itza-from-bacalar",
    title: { en: "Chichén Itzá · from Bacalar", es: "Chichén Itzá · desde Bacalar" },
    tagline: { en: "World Wonder · very long day from Bacalar, worth every minute", es: "Maravilla Mundial · día muy largo desde Bacalar, vale cada minuto" },
    category: "ruins",
    audience: ["regular"],
    location: "From Bacalar (~5h each way)",
    duration: 13,
    priceAdult: 210,
    priceKid: 115,
    rating: 4.8,
    reviews: 2401,
    tags: ["ruins", "wonder", "mayan", "from-bacalar"],
    includes: ["Transfer", "Guide", "Entry", "Buffet lunch", "Cenote Ik Kil"],
    times: ["05:30"],
    color: "clay",
    phLabel: "CHICHÉN · FROM BACALAR",
    pickupPoints: [
      { label: { en: "Bacalar · hotel zone", es: "Bacalar · zona hotelera"  }, surcharge: 0, etaMin: 0 }
    ]
  },
  {
    id: "chichen-riviera",
    slug: "chichen-itza-from-riviera",
    title: { en: "Chichén Itzá · from Riviera Maya", es: "Chichén Itzá · desde Riviera Maya" },
    tagline: { en: "World Wonder day-trip from Cancún, Playa del Carmen or Tulum", es: "Maravilla Mundial desde Cancún, Playa del Carmen o Tulum" },
    category: "ruins",
    audience: ["regular"],
    location: "From Cancún / Playa / Tulum",
    duration: 11,
    priceAdult: 110,
    priceKid: 65,
    rating: 4.8,
    reviews: 1840,
    tags: ["ruins", "wonder", "mayan", "day-trip"],
    includes: ["Transfer from Riviera Maya", "Bilingual guide", "Entry fees", "Buffet lunch", "Cenote Ik Kil"],
    times: ["05:30", "06:00"],
    color: "clay",
    phLabel: "CHICHÉN · RIVIERA",
    pickupPoints: [
      { label: { en: "Cancún · hotel zone",    es: "Cancún · zona hotelera"   }, surcharge: 0,  etaMin: 0  },
      { label: { en: "Playa del Carmen",       es: "Playa del Carmen"         }, surcharge: 15, etaMin: 45 },
      { label: { en: "Tulum town",             es: "Tulum · centro"           }, surcharge: 25, etaMin: 90 }
    ]
  },
  {
    id: "mahahual-beach-club",
    slug: "mahahual-beach-club-day",
    title: { en: "Mahahual Beach Club · Port Day", es: "Club de Playa Mahahual · Día Puerto" },
    tagline: { en: "Beach beds, snorkel, drinks — 5 min from pier", es: "Camastros, snorkel, bebidas — 5 min del muelle" },
    category: "beach",
    audience: ["port"],
    location: "Mahahual beachfront",
    duration: 5,
    priceAdult: 69,
    priceKid: 39,
    rating: 4.7,
    reviews: 734,
    tags: ["port-friendly", "beach", "all-inclusive"],
    includes: ["Shuttle from pier", "Beach bed & umbrella", "Snorkel gear", "Open bar (4hrs) + lunch"],
    times: ["09:00", "10:00", "11:00"],
    portReturn: "15:30",
    color: "lagoon",
    phLabel: "BEACH CLUB",
    pickupPoints: [
      { label: { en: "Mahahual cruise pier", es: "Muelle cruceros Mahahual" }, surcharge: 0, etaMin: 5  },
      { label: { en: "Costa Maya resorts",   es: "Resorts Costa Maya"       }, surcharge: 5, etaMin: 20 }
    ]
  },
  {
    id: "atv-jungle",
    slug: "atv-jungle-cenote",
    title: { en: "ATV Jungle + Cenote Plunge", es: "ATV Selva + Cenote" },
    tagline: { en: "Mud, speed, and a cold swim to finish", es: "Lodo, velocidad y un chapuzón helado" },
    category: "adventure",
    audience: ["port", "regular"],
    location: "20 min from Mahahual",
    duration: 3,
    priceAdult: 89,
    priceKid: null,
    rating: 4.9,
    reviews: 612,
    tags: ["port-friendly", "adrenaline", "cenote"],
    includes: ["ATV (double)", "Helmet & goggles", "Guide", "Cenote entry"],
    times: ["08:30", "10:30", "12:30"],
    portReturn: "14:30",
    color: "sun",
    phLabel: "ATV · JUNGLE",
    pickupPoints: [
      { label: { en: "Mahahual cruise pier",  es: "Muelle cruceros Mahahual" }, surcharge: 0, etaMin: 10 },
      { label: { en: "Costa Maya resorts",    es: "Resorts Costa Maya"       }, surcharge: 5, etaMin: 20 }
    ]
  },
  {
    id: "snorkel-reef",
    slug: "snorkel-mahahual-reef",
    title: { en: "Snorkel · Mesoamerican Reef", es: "Snorkel · Arrecife Mesoamericano" },
    tagline: { en: "Second-largest reef on the planet — 2 stops · shared boat", es: "Segundo arrecife del planeta — 2 paradas · bote compartido" },
    category: "ocean",
    audience: ["port", "regular"],
    location: "Mahahual reef",
    duration: 3,
    priceAdult: 49,
    priceKid: 29,
    rating: 4.8,
    reviews: 521,
    tags: ["port-friendly", "snorkel", "reef"],
    includes: ["Shared boat", "Gear", "Guide", "Fruit & water", "Marine park fee"],
    times: ["09:00", "11:00", "13:00"],
    portReturn: "15:00",
    color: "deep",
    phLabel: "REEF · SNORKEL",
    pickupPoints: [
      { label: { en: "Mahahual cruise pier",  es: "Muelle cruceros Mahahual" }, surcharge: 0, etaMin: 5  },
      { label: { en: "Costa Maya resorts",    es: "Resorts Costa Maya"       }, surcharge: 5, etaMin: 15 }
    ]
  },
  {
    id: "ichkabal",
    slug: "ichkabal-new-mayan-ruins",
    title: { en: "Ichkabal · Newly Opened Ruins", es: "Ichkabal · Ruinas Recién Abiertas" },
    tagline: { en: "Recently excavated (2024) Maya city emerging from jungle · small group", es: "Ciudad maya recién excavada (2024) emergiendo de la selva · grupo pequeño" },
    category: "ruins",
    audience: ["regular", "port"],
    location: "SW of Bacalar",
    duration: 5,
    priceAdult: 95,
    priceKid: 55,
    rating: 4.8,
    reviews: 45,
    tags: ["ruins", "mayan", "new-2024", "jungle"],
    includes: ["Van & driver", "Archaeologist guide", "Entry fees", "Water & fruit"],
    times: ["08:00", "10:00"],
    color: "clay",
    phLabel: "ICHKABAL · NEW 2024",
    pickupPoints: [
      { label: { en: "Bacalar · hotel zone",  es: "Bacalar · zona hotelera"  }, surcharge: 0,  etaMin: 0  },
      { label: { en: "Mahahual cruise pier",  es: "Muelle cruceros Mahahual" }, surcharge: 40, etaMin: 75 }
    ]
  },
  {
    id: "muyil-float",
    slug: "muyil-sian-kaan-floating-canals",
    title: { en: "Muyil · Sian Ka'an Floating Canals", es: "Muyil · Canales Flotantes Sian Ka'an" },
    tagline: { en: "Drift the ancient Maya canal in a life vest · biosphere reserve", es: "Flota por el canal maya antiguo en chaleco · reserva de biósfera" },
    category: "adventure",
    audience: ["regular"],
    location: "Between Tulum and Bacalar",
    duration: 5,
    priceAdult: 120,
    priceKid: 70,
    rating: 4.9,
    reviews: 287,
    tags: ["sian-kaan", "float", "nature", "mayan"],
    includes: ["Park entry", "Life vest", "Local guide", "Water & fruit", "Muyil ruins entry"],
    times: ["08:00", "10:30"],
    color: "lagoon",
    phLabel: "MUYIL · SIAN KA'AN",
    pickupPoints: [
      { label: { en: "Tulum town · centre",   es: "Tulum · centro"           }, surcharge: 0,  etaMin: 0  },
      { label: { en: "Bacalar · hotel zone",  es: "Bacalar · zona hotelera"  }, surcharge: 30, etaMin: 120 },
      { label: { en: "Playa del Carmen",       es: "Playa del Carmen"         }, surcharge: 20, etaMin: 60 }
    ]
  },
  {
    id: "dzibanche",
    slug: "dzibanche-kinichna-twin-pyramids",
    title: { en: "Dzibanché + Kinichná · Twin Pyramids", es: "Dzibanché + Kinichná · Pirámides Gemelas" },
    tagline: { en: "Less-crowded alternative to Kohunlich · twin ruin sites", es: "Alternativa menos multitudinaria a Kohunlich · sitios gemelos" },
    category: "ruins",
    audience: ["port", "regular"],
    location: "1h30 from Mahahual",
    duration: 6,
    priceAdult: 85,
    priceKid: 45,
    rating: 4.8,
    reviews: 124,
    tags: ["ruins", "mayan", "port-friendly", "off-the-beaten"],
    includes: ["AC van", "Bilingual guide", "Entry (both sites)", "Water"],
    times: ["08:30", "10:30"],
    portReturn: "14:30",
    color: "jungle",
    phLabel: "DZIBANCHÉ · TWIN",
    pickupPoints: [
      { label: { en: "Mahahual cruise pier",  es: "Muelle cruceros Mahahual" }, surcharge: 0,  etaMin: 10 },
      { label: { en: "Bacalar · hotel zone",  es: "Bacalar · zona hotelera"  }, surcharge: 15, etaMin: 50 }
    ]
  },
  {
    id: "transfer-cun",
    slug: "private-transfer-cancun-airport",
    title: { en: "Private Transfer · Cancún Airport", es: "Traslado Privado · Aeropuerto Cancún" },
    tagline: { en: "Cancún ⇄ Bacalar · private van, up to 8 pax", es: "Cancún ⇄ Bacalar · van privada, hasta 8 pax" },
    category: "transfer",
    audience: ["regular"],
    location: "CUN → Bacalar / Tulum / Mahahual",
    duration: 4,
    priceAdult: 320,
    priceKid: 0,
    flat: true,
    rating: 4.9,
    reviews: 1803,
    tags: ["airport", "private", "van"],
    includes: ["Door-to-door", "Flight tracking", "Water & wifi", "Free child seat"],
    times: ["Any time — 24/7"],
    color: "jungle",
    phLabel: "VAN · CUN"
  },
  {
    id: "transfer-tulum",
    slug: "private-transfer-tulum-airport",
    title: { en: "Private Transfer · Tulum Airport", es: "Traslado Privado · Aeropuerto Tulum" },
    tagline: { en: "TQO ⇄ Bacalar/Mahahual · 90 min door-to-door", es: "TQO ⇄ Bacalar/Mahahual · 90 min puerta a puerta" },
    category: "transfer",
    audience: ["regular"],
    location: "TQO → Bacalar / Mahahual",
    duration: 2,
    priceAdult: 140,
    priceKid: 0,
    flat: true,
    rating: 4.9,
    reviews: 412,
    tags: ["airport", "private", "van"],
    includes: ["Door-to-door", "Flight tracking", "Water & wifi"],
    times: ["Any time — 24/7"],
    color: "deep",
    phLabel: "VAN · TQO"
  }
];

window.REVIEWS = [
  { tour: "sailboat-bacalar", name: "Marta G.", flag: "🇪🇸", rating: 5, date: "Mar 2026", body: { en: "Captain Beto was the soul of the trip. The water really is seven colors — photos don't lie.", es: "El capitán Beto fue el alma del viaje. El agua es realmente de siete colores." } },
  { tour: "sailboat-bacalar", name: "James T.", flag: "🇺🇸", rating: 5, date: "Feb 2026", body: { en: "Booked day-of via WhatsApp, they picked us up at our hotel 20 min later. Unreal.", es: "Reservé el mismo día por WhatsApp, nos recogieron en 20 min." } },
  { tour: "chacchoben-port", name: "Linda P.", flag: "🇺🇸", rating: 5, date: "Apr 2026", body: { en: "Our ship was Carnival Horizon. We were back at the pier with 90 min to spare and felt zero stress.", es: "Nuestro barco era Carnival Horizon. Volvimos al muelle con 90 min de sobra, cero estrés." } },
  { tour: "atv-jungle", name: "Kai S.", flag: "🇩🇪", rating: 5, date: "Mar 2026", body: { en: "Muddy, fast, incredible. The cenote at the end was freezing and perfect.", es: "Lodoso, rápido, increíble. El cenote al final estaba helado y perfecto." } },
  { tour: "pontoon-rapids", name: "Sofía M.", flag: "🇲🇽", rating: 5, date: "Feb 2026", body: { en: "El pontón privado fue el highlight de nuestra luna de miel. El ceviche, divino.", es: "El pontón privado fue el highlight de nuestra luna de miel. El ceviche, divino." } },
  { tour: "muyil-float", name: "Elena R.", flag: "🇲🇽", rating: 5, date: "Apr 2026", body: { en: "Flotar por el canal con el sonido de la selva fue meditativo. Lo mejor del viaje.", es: "Flotar por el canal con el sonido de la selva fue meditativo. Lo mejor del viaje." } },
  { tour: "ichkabal", name: "Ben H.", flag: "🇬🇧", rating: 5, date: "Mar 2026", body: { en: "Being on top of a freshly-uncovered pyramid with no one around is surreal. Go before the crowds find it.", es: "Estar en una pirámide recién descubierta, sin nadie, es surreal. Ve antes de que la encuentren." } }
];

window.MAP_PINS = [
  { id: "bacalar",    name: "Bacalar",       x: 41.79, y: 70.87, count: 7, label: { en: "Lagoon Tours",        es: "Tours Laguna"          } },
  { id: "mahahual",   name: "Mahahual",      x: 60.87, y: 75.02, count: 5, label: { en: "Port · Beach · ATV",   es: "Puerto · Playa · ATV" } },
  { id: "chacchoben", name: "Chacchoben",    x: 51.92, y: 66.89, count: 1, label: { en: "Mayan Ruins",          es: "Ruinas Mayas"         } },
  { id: "kohunlich",  name: "Kohunlich",     x: 25.83, y: 88.35, count: 1, label: { en: "Temple of Masks",      es: "Templo Mascarones"    } },
  { id: "ichkabal",   name: "Ichkabal",      x: 47.50, y: 80.04, count: 1, label: { en: "New ruins (2024)",     es: "Ruinas nuevas (2024)" } },
  { id: "dzibanche",  name: "Dzibanché",     x: 29.98, y: 78.31, count: 1, label: { en: "Twin pyramids",         es: "Pirámides gemelas"   } },
  { id: "muyil",      name: "Muyil",         x: 51.14, y: 52.35, count: 1, label: { en: "Sian Ka'an floats",     es: "Canales Sian Ka'an"  } },
  { id: "tulum",      name: "Tulum",         x: 60.09, y: 32.62, count: 2, label: { en: "Ruins + TQO Airport",  es: "Ruinas + Aeropuerto"  } },
  { id: "cancun",     name: "Cancún",        x: 69.18, y:  9.09, count: 2, label: { en: "CUN Airport",          es: "Aeropuerto CUN"       } },
  { id: "chichen",    name: "Chichén Itzá",  x: 30.50, y: 21.03, count: 2, label: { en: "World Wonder",         es: "Maravilla"            } }
];
